### ISSUE TITLE
GTAUtil path bug

### ISSUE THREAD

**Issue by vscorpio** [vscorpio/gta5rpf-to-fivem#2]
I'm aware of a GTAUtil bug that happens at some poeple -> doesn't let you propely set the path, thus resulting in the tool not working. This issue is not easily reproductible, I'm investigating.

**Comment by vscorpio** [comment]
A fix to this issue could consist in rebuilding the GTAUtil tool and changing the default .NET User.config location which is stored in 
**C:\Users\username\AppData\Local\GTAUtil\GTAUtil.exe_Url_qpjyuu5cymk0y4dupg0s1xcbnpjrame4\2.2.7.0**
Note that the _qpjyuu5cymk0y4dupg0s1xcbnpjrame4_ is changing everytime the application directory is moved.

This is the file that represents the GTAV folder (needed) to decrypt the RPF archives.
I am trying to address this issue.

3 more users reported this issue.

One (eventually) fixed the issue:
> I just uninstalled everything then waited a few hours installed it again and it works now
I don't know exactly what he did or what he uninstalled.
This issue does not happen on every computer and I didn't find a pattern yet.

I will try to rebuild the GTAUtil tool to the tool's needs.

**Comment by vscorpio** [comment]
I thought that it is related to Windows Version as well at first. But upon further testing it seems that is the windows version doesn't make any difference, there's something else to it. There are some cases in which two users share the same version but only one of them is able to set the GTAV Folder.

![image|475x385](upload://plRnqG9hrqhb8s82b30EjPHcS4r.png) 

![image|462x500](upload://grdFnxbTmSOkHB6TatPPMWNLrOs.png) 

![image|466x343](upload://3YueBbyAsoUisbwifFjB6iJauFt.png)

**Comment by adieboy** [comment]
how can i install GTAUtil

**Comment by GamingNerdLeith2020** [comment]
I still have this issue but my version is EGS and not R* or Steam
